### PR TITLE
* Merged shell-escape-fix

### PR DESCRIPTION
**Pull request by bozhinov**
- shell escape fix + some code styling.

### CODE REVIEW

**Comment by bozhinov** [comment]
@olevole  I would check lines 1387 & 2003 from clonos.php
during the refactoring I believe  I ve uncovered some bugs
just does not seem right

**Comment by olevole** [comment]
@bozhinov lines 2003: do you mean this line: https://github.com/clonos/control-pane/blob/aef78b712561759469ab09d713cff967b6db212d/php/clonos.php#L2003

This is an intermediate/temporary SQLite3 file that is used for dynamic parameters for puppet module. When a container is created with filled parameters of a third-party service, the puppet module works inside the container and makes all the settings. This SQlite3 file is needed to bootstrap such a container

**Comment by bozhinov** [comment]
No, I ve created separate issues both
I m also in the process of installing a test bed so I can test the entire refactoring I ve done.

**Comment by olevole** [comment]
checking the proposed code in a working environment is very much appreciated))

**Comment by bozhinov** [comment]
if I can get it to work. The info in the distfile for the cbsd puppet plugin is incorrect for starters

**Comment by bozhinov** [comment]
Please help me get ClonOS running, so I can test this. All problems I encounters have been recorded here

**Comment by olevole** [comment]
@bozhinov sorry for the delay. Can you write down the details, what exactly is the problem? I think in the next week I will be able to update the image and instructions.

**Comment by bozhinov** [comment]
I tried installing ClonOS in a VM so I can test my commits
I followed the instructions and I failed
All issues I encountered I recorded as issues here and in ports and www repos

**Comment by bozhinov** [comment]
@olevole  This has been tested and is ready for use

**Comment by olevole** [comment]
Now everything seems to be in order in the code. However, for some reason the system writes the conflict to the php/clonos.php file and the merge is blocked. I am trying to understand why

**Comment by bozhinov** [comment]
What's failing ? I have a test setup now so I can fix it in no time

**Comment by bozhinov** [comment]
I would suggest you copy all files from my repo->fix branch and copy them over your master branch
then commit them yourself. that will do it

**Comment by olevole** [comment]
@bozhinov done, thanks for your work and improvements. We plan to release a new ClonOS build after FreeBSD 13.0-RELEASE ( https://www.freebsd.org/releases/13.0R/schedule/ )

**Comment by bozhinov** [comment]
Perfect. I plan on helping a bit more with this as I m looking to replace ESXi 6.5 (EOL Dec 2021)

**Comment by olevole** [comment]
We only have 9 months left to write another ESXi, we need to strain ;)

**Comment by bozhinov** [comment]
It's more like 2 months. Until the weather gets warmer and then it is off to the garden for me.
Those tomatoes ain't gonna grow themselves :)

**Pull request merged**
