### PR TITLE
Extracted Menu from ClonOS

### PR DESCRIPTION
**Pull request by bozhinov**
Somehow a bunch of code from the previous commit was not merged
this pull adds that code

Also:
- Menu class no longer under ClonOS
- Lang code extracted to a separate class

### CODE REVIEW

**Review by olevole — APPROVED** [review]

**Comment by olevole** [comment]
@bozhinov current revision leads to:
```
PHP Fatal error:  Cannot declare class Locale, because the name is already in use in /usr/local/www/clonos/php/locale.php on line 3
```

can you double check pls?

**Comment by bozhinov** [comment]
@olevole  I m running the same code and it is fine here
Where do I click to recreate it ?

**Comment by olevole** [comment]
@bozhinov can you contact me by mail (olevole at olevole dot ru ) or telegram (/olevole)?
I think we can make an account for you on the server, which is rented for development at the expense of the project donors.
Also, it will solve the problem with your test lab if you plan to participate in the future.

**Comment by olevole** [comment]
@bozhinov well, Locale class error occurs when a php80-intl package is installed ( needed for namespaces or just uninstall php80-intl ).
However, the latest changes still break the system. Unfortunately, I still could not get an email response from you to demonstrate this.

**Comment by bozhinov** [comment]
OK that makes sense. I will rename that class
Weirdly enough I did respond to your e-mail and also messaged you on Telegram.
I will try again

**Pull request merged**
